public struct CardsMock {
    public static var multipleTypeCards = [Card(content: .creditCard(.init(number: "**** **** **** **21",
                                                                           validDate: "09/25",
                                                                           name: Strings.CreditCard.ownerName,
                                                                           brand: Strings.CreditCard.brandVisa,
                                                                           style: .standard))),
                                           Card(content: .info(.init(headline: Strings.CardInfo.rewardsHeadline,
                                                                     title: Strings.CardInfo.rewardsTitle,
                                                                     caption: Strings.CardInfo.rewardsCaption,
                                                                     icon: "gift",
                                                                     button: Strings.CardInfo.redeem,
                                                                     color: .primaryColor))),
                                           Card(content: .info(.init(headline: Strings.CardInfo.monthlySpendingHeadline,
                                                                     title: Strings.CardInfo.monthlySpendingTitle,
                                                                     caption: Strings.CardInfo.monthlySpendingCaption,
                                                                     icon: "chart.pie.fill",
                                                                     button: Strings.CardInfo.monthlySpendingButton,
                                                                     color: .secondaryColor))),
                                           Card(content: .creditCard(.init(number: "**** **** **** **73",
                                                                           validDate: "02/29",
                                                                           name: Strings.CreditCard.ownerNameTwo,
                                                                           brand: Strings.CreditCard.brandMastercard,
                                                                           style: .black))),
                                           Card(content: .info(.init(headline: Strings.CardInfo.specialOfferHeadline,
                                                                     title: Strings.CardInfo.specialOfferTitle,
                                                                     caption: Strings.CardInfo.specialOfferCaption,
                                                                     icon: "shield.fill",
                                                                     button: Strings.CardInfo.learnMore,
                                                                     color: .accentColorB))),
                                           Card(content: .info(.init(headline: Strings.CardInfo.noCreditCardHeadline,
                                                                     title: Strings.CardInfo.noCreditCardTitle,
                                                                     caption: Strings.CardInfo.noCreditCardCaption,
                                                                     icon: "star.fill",
                                                                     button: Strings.CardInfo.applyNow,
                                                                     color: .secondaryColor)))
    ]
    
    public static var creditCardMocks = [Card(content: .creditCard(.init(number: "**** **** **** **21",
                                                                         validDate: "09/25",
                                                                         name: Strings.CreditCard.ownerName,
                                                                         brand: Strings.CreditCard.brandVisa,
                                                                         style: .platinum))),
                                         Card(content: .creditCard(.init(number: "**** **** **** **73",
                                                                         validDate: "02/29",
                                                                         name: Strings.CreditCard.ownerNameTwo,
                                                                         brand: Strings.CreditCard.brandMastercard,
                                                                         style: .gold)))
    ]
}
